version: '3'
services:
  webapp:
    build: node
    image: node-express-dev:1.0
    tty: true
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ../v3/:/usr/var/app
      - ./vscode-data/:/root/.vscode-server
  http:
    build:
      context: ./http
      dockerfile: ./Dockerfile
    volumes:
      - ../v3/dist/:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
